# Generated by Django 5.0.3 on 2024-04-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_alter_shortenedurl_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='custom_short_url',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
