# Generated by Django 5.0.3 on 2024-04-23 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_remove_shortenedurl_custom_short_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='user',
        ),
    ]
