# Generated by Django 5.0.3 on 2024-04-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_shortenedurl_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
